version: '3.8'

services:
  scraping-service:
    build:
      context: ./scraping_service
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "5001:5001"
    depends_on:
      - data-processing-service
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    networks:
      - app-network

  data-processing-service:
    build:
      context: ./data_processing_service
    ports:
      - "5002:5002"
    depends_on:
      - storage-service
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      PYTHONPATH: /app
    networks:
      - app-network

  storage-service:
    build:
      context: ./storage_service
    ports:
      - "5003:5003"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  web-service:
    build:
      context: ./web_service
    ports:
      - "5004:5000"
    depends_on:
      - scraping-service
    networks:
      - app-network

  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
